project:
  type: website
  output-dir: docs

website:
  title: "What Statistical Model Should I Use?"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: modules/module_1_data_cleaning.qmd
        text: Module 1
      - href: modules/module_2_missingness.qmd
        text: Module 2
      - href: modules/module_3_regression_glm.qmd
        text: Module 3
      - href: modules/module_4_classification_clustering.qmd
        text: Module 4
      - href: modules/module_5_full_analysis.qmd
        text: Module 5
      - href: modules/module_6_causal_inference.qmd
        text: Module 6

format:
  html:
    theme: cosmo
    lang:  fr
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: false
    df-print: paged

